# This is a basic workflow to help you get started with github actions.

name: CI

# Controls when the actions run.
on: 
  # Triggers the workflow on push or pull-requests events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #1: lint job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo Lint in progress..

  #2: Unit test
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit test
        run: echo Unit testing in progress..

  #3: Instrumentation test
  instrumentation-test:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Intrusmentation test
        run: echo Instrumentation test in progress..

  #4: Static code analysis
  static-code-analysis:
    needs: [ instrumentation-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: SonarCloud Scan
        run: ./gradlew androidApp:sonarqube -Dsonar.login=${{ secrets.SONARCLOUD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}